# Generated by Django 4.0.3 on 2022-04-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0002_alter_elemento_estado_alter_elemento_tipoingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=10)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
        ),
    ]
