# Generated by Django 4.0.3 on 2022-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bajas', '0002_remove_baja_elemento_detallebaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallebaja',
            name='autorizado',
            field=models.BooleanField(default=True),
        ),
    ]
