# Generated by Django 4.0.3 on 2022-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bajas', '0004_detallebaja_fechaborrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallebaja',
            name='fechaBorrado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
