# Generated by Django 4.0.3 on 2022-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Por Asignar', 'Pendiente'), ('En mantenimiento', 'Mantenimiento'), ('En Proceso de Baja', 'Baja')], default='Por Asignar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipoIngreso',
            field=models.CharField(choices=[('Donacion', 'Donacion'), ('Compra directa', 'Compra'), ('Comodato', 'Comodato'), ('Transferencia tecnológica', 'Transferencia'), ('Traspaso de otra Sede', 'Traspaso')], default='Compra directa', max_length=150, verbose_name='¿Cómo fue adquirido el elemento?'),
        ),
    ]
