# Generated by Django 4.0.3 on 2022-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_elemento_estado_alter_elemento_tipoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
