# Generated by Django 4.0.3 on 2022-04-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_traspaso_detallestraspaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='traspaso',
            name='procedencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.asignacion'),
        ),
    ]
