# Generated by Django 4.0.3 on 2022-04-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_traspaso_procedencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traspaso',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='traspaso',
            name='procedencia',
        ),
        migrations.DeleteModel(
            name='DetallesTraspaso',
        ),
        migrations.DeleteModel(
            name='Traspaso',
        ),
    ]
