# Generated by Django 4.0.3 on 2022-04-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0002_alter_elemento_estado_alter_elemento_tipoingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=50000)),
                ('observaciones', models.CharField(max_length=50000)),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.elemento')),
            ],
        ),
    ]
