# Generated by Django 4.0.3 on 2022-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(default='En Progreso', max_length=100),
        ),
    ]
